# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=-1)),
                ('gender', models.CharField(choices=[('men', 'Men Only'), ('women', 'Women Only'), ('both', 'Men / Women'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
